CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_number VARCHAR(34) NOT NULL UNIQUE,

    balance NUMERIC(19, 2) NOT NULL DEFAULT 0.00,

    user_id BIGINT NOT NULL,

    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);