CREATE TABLE transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    from_account_id BIGINT NOT NULL,

    to_account_id BIGINT NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfers_from_account
        FOREIGN KEY (from_account_id)
        REFERENCES accounts(id),

    CONSTRAINT fk_transfers_to_account
        FOREIGN KEY (to_account_id)
        REFERENCES accounts(id),

    CONSTRAINT chk_transfers_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_transfers_different_accounts
        CHECK (from_account_id <> to_account_id)
);