CREATE TABLE transfer_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    idempotency_key VARCHAR(255) NOT NULL,

    user_id BIGINT NOT NULL,

    request_hash VARCHAR(64) NOT NULL,

    status VARCHAR(20) NOT NULL,

    transfer_id BIGINT,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_transfer_idempotency_key
        UNIQUE (idempotency_key),

    CONSTRAINT fk_transfer_idempotency_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_transfer_idempotency_transfer
        FOREIGN KEY (transfer_id)
        REFERENCES transfers(id),

    CONSTRAINT chk_transfer_idempotency_status
        CHECK (status IN ('PENDING', 'COMPLETED'))
);